# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beamlit < Formula
  desc ""
  homepage "https://www.beamlit.com"
  version "0.0.6-dev"

  on_macos do
    on_intel do
      url "https://github.com/tmp-moon/toolkit/releases/download/0.0.6-dev/beamlit_Darwin_x86_64.tar.gz"
      sha256 "b68c3397b41754c02ce491babc6e31d564f7cf3d1b7d7c0f6618434970dfecf1"

      def install
        bin.install "beamlit"
      end
    end
    on_arm do
      url "https://github.com/tmp-moon/toolkit/releases/download/0.0.6-dev/beamlit_Darwin_arm64.tar.gz"
      sha256 "9a06a4aa5f339bb435ef8894830e4830cf6680f6a0795eb07cb923b69eaae734"

      def install
        bin.install "beamlit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmp-moon/toolkit/releases/download/0.0.6-dev/beamlit_Linux_x86_64.tar.gz"
        sha256 "cf59b7adcea54340f0a5c1e9adbffd4a42849921facdbee6f5c9e78027c0cd9f"

        def install
          bin.install "beamlit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmp-moon/toolkit/releases/download/0.0.6-dev/beamlit_Linux_arm64.tar.gz"
        sha256 "b4b90e372b2218b450f77b0d69f5e7dd1849fa9bf6cbef363ae65d0e46d0de6e"

        def install
          bin.install "beamlit"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Beamlit is a tool to ship AI agents that never slack.
    EOS
  end
end
