# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beamlit < Formula
  desc ""
  homepage "https://www.beamlit.com"
  version "0.0.11-dev"

  on_macos do
    on_intel do
      url "https://github.com/tmp-moon/toolkit/releases/download/0.0.11-dev/beamlit_Darwin_x86_64.tar.gz"
      sha256 "8274911bb7861536e80b9642c23526fce75bd90867caec4532ee3a14c082e55c"

      def install
        bin.install "beamlit"
      end
    end
    on_arm do
      url "https://github.com/tmp-moon/toolkit/releases/download/0.0.11-dev/beamlit_Darwin_arm64.tar.gz"
      sha256 "d5f53062ab582b041349872a972638749c0a223d60534b31785a0624619d9d33"

      def install
        bin.install "beamlit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmp-moon/toolkit/releases/download/0.0.11-dev/beamlit_Linux_x86_64.tar.gz"
        sha256 "d83c42ef2cfe62fecb63f640e24489ccf55041e7378e91ab5f9c63da3c153bd1"

        def install
          bin.install "beamlit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmp-moon/toolkit/releases/download/0.0.11-dev/beamlit_Linux_arm64.tar.gz"
        sha256 "92799e4db1cfd65201466b6d7e5430cf67b6841384056044d20ae0db49283c5a"

        def install
          bin.install "beamlit"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Beamlit is a tool to ship AI agents that never slack.
    EOS
  end
end
